language: node_js

node_js:
  - "node"

services:
  - docker

#sudo: false
#before_install:
#  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
#  - export PATH=$HOME/.yarn/bin:$PATH
#cache:
#  yarn: true

cache:
  yarn

env:
  global:
    # Do not prompt for user input when using any SDK methods.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 

install:
  - yarn

stages:
  - name: lint
  - name: test
  - name: push to dockerhub
    if: branch = master

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test 
      script: yarn test
    - stage: push to dockerhub
      script: ./push_dockerhub.sh
      deploy:
        provider: script
        script: ./deploy.sh       
      on:
        branch: master

