language: node_js
node_js:
- node
services:
- docker
cache: yarn
install:
- yarn
stages:
- name: lint
- name: test
- name: push to dockerhub
  if: branch = master
- name: deploy to gcp
  if: branch = master
jobs:
  include:
  - stage: lint
    script: yarn lint
  - stage: test
    script: yarn test
  - stage: push to dockerhub
    script: 
      - set -x
    script: "./push_dockerhub.sh"
  - stage: deploy to gcp
    script: "./deploy"
before_install:
- openssl aes-256-cbc -K $encrypted_a61b52fb7c59_key -iv $encrypted_a61b52fb7c59_iv
  -in deploy_key.enc -out deploy_key -d
